part of 'edit_profile_bloc.dart';

@freezed
class EditProfileWithInitialState with _$EditProfileWithInitialState {
  const factory EditProfileWithInitialState({
    required String message,
    required bool isFailure,
  required GlobalKey<FormState> formKeyForScaffold ,
  required GlobalKey<FormState> formKeyForBottomSheet,
    required TextEditingController firstNameController,
    required TextEditingController lastNameController,
    required TextEditingController mobileNumberController,
    required TextEditingController emailController,
    required TextEditingController addressController,
    required TextEditingController birthDayController,
    required FocusNode firsNameFocusNode,
    required FocusNode lastNameFocusNode,
    required FocusNode mobileNumberFocusNode,
    required FocusNode emailFocusNode,
    required FocusNode addressFocusNode,
    required FocusNode birthdayFocusNode,
    required bool isFirstNameInvalid,
    required bool isLastNameInvalid,
    required bool isMobileNumberInvalid,
    required bool isEmailInvalid,
    required bool isAddressInvalid,
    required bool isBirthdayInvalid,
    required bool hasFocusMobileNumberField,

    required bool isLoading,
    required bool isBottomSheetLoading,
    required String? invalidMobileNumberError,
    required String? imageUrl,
    required File? fileImage,
    required int minLength,
    required String code,
  }) = _EditProfileWithInitialState;

  factory EditProfileWithInitialState.initial() => EditProfileWithInitialState(
      message: '',
      isFailure: false,
      isLoading: false,
      formKeyForScaffold: GlobalKey<FormState>(),
      formKeyForBottomSheet: GlobalKey<FormState>(),
      isBottomSheetLoading: false,
      invalidMobileNumberError: null,
      fileImage: null,
      imageUrl: null,
      firstNameController: TextEditingController(),
      lastNameController: TextEditingController(),
      mobileNumberController: TextEditingController(),
      emailController: TextEditingController(),
      addressController: TextEditingController(),
      birthDayController: TextEditingController(),
      birthdayFocusNode: FocusNode(),
      firsNameFocusNode: FocusNode(),
      lastNameFocusNode: FocusNode(),
      mobileNumberFocusNode: FocusNode(),
      emailFocusNode: FocusNode(),
      addressFocusNode: FocusNode(),
      isFirstNameInvalid: false,
      isLastNameInvalid: false,
      isMobileNumberInvalid: false,
      isEmailInvalid: false,
      isAddressInvalid: false,
      isBirthdayInvalid: false,
      hasFocusMobileNumberField: false,

      code: '49',
      minLength: 9);
}
