on:
  push:
    branches:
      - production

name: Flutter Bloc Template Android CI/CD
jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    env:
      KEYSTORE: ${{ secrets.KEYSTORE }}
      KEY_PATH: ${{ secrets.KEY_PATH}}
      KEY_PASS: ${{ secrets.KEY_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      STORE_PASS: ${{ secrets.KEYSTORE_PASSWORD }}
      CREDENTIAL_FILE_CONTENT: ${{ secrets.CREDENTIAL_FILE_CONTENT }}

    steps:

      - uses: actions/checkout@v3


      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'


      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version-file: pubspec.yaml # path to pubspec.yaml
      - run: flutter --version


      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV


      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - run: echo $KEYSTORE | base64 -di >  ${{secrets.KEY_PATH}}
      - run: flutter clean
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter build apk --release -t lib/main_prod.dart --flavor=prod  --split-per-abi


      - name: Upload APK Prod
        uses: actions/upload-artifact@v2.3.1
        with:
          name: ${{ env.repository_name }} -- prod apk
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-prod-release.apk

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          groups: testers
          file: build/app/outputs/flutter-apk/app-armeabi-v7a-prod-release.apk
